In [1]:

import numpy as np
import pandas as pd
from sklearn import model_selection

In [2]:
test_values=np.loadtxt("/home/kapil/Downloads/ccpp_x_test (1).csv",delimiter=',')
#change if want to change anything in this 


#til this if any
df=pd.DataFrame(test_values)
df[4]=1
finaltest=df.values
finaltest.shape

(2392, 5)

In [3]:
#for finding the train data 

train_inputs=np.loadtxt("/home/kapil/Downloads/ccpp_x_y_train (1).csv",delimiter=',')
#print(train_inputs)
y=train_inputs[:,train_inputs.shape[1]-1]
x=train_inputs[:,0:train_inputs.shape[1]-1]

print(x)
#print("\n************The output for training data is************ \n",y[0][0])

[[   8.58   38.38 1021.03   84.37]
 [  21.79   58.2  1017.21   66.74]
 [  16.64   48.92 1011.55   78.76]
 ...
 [  29.8    69.34 1009.36   64.74]
 [  16.37   54.3  1017.94   63.63]
 [  30.11   62.04 1010.69   47.96]]


In [4]:
df=pd.DataFrame(x)
df[4]=1
x=df.values
x.shape

(7176, 5)

In [5]:
m_values=(np.zeros(x.shape[1])).reshape(-1,1)
m_values
print(df.head())
print(np.dot(x,m_values))


       0      1        2      3  4
0   8.58  38.38  1021.03  84.37  1
1  21.79  58.20  1017.21  66.74  1
2  16.64  48.92  1011.55  78.76  1
3  31.38  71.32  1009.17  60.42  1
4   9.20  40.03  1017.05  92.46  1
[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]


In [8]:
def cof(x,y,final_m):

SyntaxError: invalid syntax (<ipython-input-8-65602fd3f3fa>, line 1)

In [9]:
def cost(x,y,m_values):
    total=0
    for i in range(len(x)):
        total=total+(1/len(x))*( ( y[i] - ( np.dot( x[i,:],m_values ) ).sum() )**2 )
        
    return total

In [11]:
def gd(rate,iteration,x,y):
    m_values=(np.zeros(x.shape[1])).reshape(-1,1)
    
    for i in range(iteration):
        m_values=single_gradient(rate,m_values,x,y)
        print(i," cost is ",cost(x,y,m_values))
        
    return m_values

def single_gradient(rate,m_values,x,y):
    m_slope=(np.zeros(x.shape[1]).reshape(-1,1))
    m=len(x)
    
    for i in range(len(x)):
        row=x[i,:]
        for j in range(len(m_values)):
            m_slope[j]+=(-2/m)*(y[i]-np.dot(row,m_values).sum())*row[j]
    
    return m_values-rate*m_slope

In [16]:
def run():
    rate=.000001
    iteration=200
    final_m=gd(rate,iteration,x,y)
    
    yfinal=np.zeros(len(finaltest))
    yfinal=yfinal.reshape(-1,1)
    
    print(" the value of final m is \n", final_m)
    for i in range(len(finaltest)):
        yfinal[i]=(np.dot(finaltest[i],final_m).sum())    
        
#coefficent( x,y,final_m)

    np.savetxt("project1ans.csv",yfinal,delimiter=',',fmt='%1.5f')

In [15]:
run()

0  cost is  237116.9153476344
1  cost is  271882.1255768481
2  cost is  311750.0878720959
3  cost is  357469.76702449785
4  cost is  409900.0583638327
5  cost is  470025.9229941026
6  cost is  538976.8913048112
7  cost is  618048.2823655471
8  cost is  708725.5378320655
9  cost is  812712.1275014827
10  cost is  931961.5507511968
11  cost is  1068714.0350415877
12  cost is  1225538.6209019052
13  cost is  1405381.424008927
14  cost is  1611620.98101187
15  cost is  1848131.718831461
16  cost is  2119356.739769939
17  cost is  2430391.2897751248
18  cost is  2787078.477896192
19  cost is  3196119.045120118
20  cost is  3665197.2447092105
21  cost is  4203125.198832523
22  cost is  4820008.443378939
23  cost is  5527435.7708826605
24  cost is  6338696.937955714
25  cost is  7269032.327087479
26  cost is  8335919.252964732
27  cost is  9559400.291872669
28  cost is  10962459.802184315
29  cost is  12571455.70926189
30  cost is  14416614.666299786
31  cost is  16532599.89321231
32  cost is

249  cost is  1.5301060263536014e+20
250  cost is  1.7546898541010138e+20
251  cost is  2.01223734241642e+20
252  cost is  2.3075867867769297e+20
253  cost is  2.6462866314333386e+20
254  cost is  3.034699702663718e+20
255  cost is  3.480122741034784e+20
256  cost is  3.9909234782065944e+20
257  cost is  4.576697833411768e+20
258  cost is  5.248450182705137e+20
259  cost is  6.018800087530149e+20
260  cost is  6.902219366209472e+20
261  cost is  7.915303961993924e+20
262  cost is  9.077085714991495e+20
263  cost is  1.0409389894933035e+21
264  cost is  1.1937245211398227e+21
265  cost is  1.3689354003966297e+21
266  cost is  1.5698631445299918e+21
267  cost is  1.800282388664579e+21
268  cost is  2.064521796201668e+21
269  cost is  2.3675453772302474e+21
270  cost is  2.7150457425815504e+21
271  cost is  3.1135510454012876e+21
272  cost is  3.570547619246314e+21
273  cost is  4.094620616590114e+21
274  cost is  4.695615289775499e+21
275  cost is  5.384821944245274e+21
276  cost is  6.1

475  cost is  4.235836682871854e+33
476  cost is  4.8575585763666525e+33
477  cost is  5.57053472298541e+33
478  cost is  6.388159115766641e+33
479  cost is  7.325791673098232e+33
480  cost is  8.401046790644334e+33
481  cost is  9.634124245952874e+33
482  cost is  1.104818867213328e+34
483  cost is  1.2669804729405293e+34
484  cost is  1.4529436149669392e+34
485  cost is  1.6662018029162421e+34
486  cost is  1.9107613120310597e+34
487  cost is  2.191216445189583e+34
488  cost is  2.512835841628792e+34
489  cost is  2.881661453772063e+34
490  cost is  3.304622051543614e+34
491  cost is  3.789663386465301e+34
492  cost is  4.34589746080265e+34
493  cost is  4.983773705935163e+34
494  cost is  5.715275285713488e+34
495  cost is  6.554144212564745e+34
496  cost is  7.516139505384084e+34
497  cost is  8.619333238975094e+34
498  cost is  9.884450046633872e+34
499  cost is  1.1335256453783235e+35
500  cost is  1.299900735669073e+35
501  cost is  1.490695803383426e+35
502  cost is  1.70949513

701  cost is  1.1726188966605326e+47
702  cost is  1.344731963183529e+47
703  cost is  1.5421072080257525e+47
704  cost is  1.768452528944898e+47
705  cost is  2.0280200564884645e+47
706  cost is  2.325686034656146e+47
707  cost is  2.6670424261779467e+47
708  cost is  3.0585019633077643e+47
709  cost is  3.5074186176193838e+47
710  cost is  4.0222257519555755e+47
711  cost is  4.612594549855971e+47
712  cost is  5.289615698725209e+47
713  cost is  6.0660077398464775e+47
714  cost is  6.956355999311154e+47
715  cost is  7.977386588428074e+47
716  cost is  9.148280620993918e+47
717  cost is  1.0491034550319259e+48
718  cost is  1.2030873395314854e+48
719  cost is  1.3796724618516349e+48
720  cost is  1.5821761558334123e+48
721  cost is  1.814402662446534e+48
722  cost is  2.0807145963838838e+48
723  cost is  2.386114902282592e+48
724  cost is  2.736340840204622e+48
725  cost is  3.137971765990441e+48
726  cost is  3.598552731251378e+48
727  cost is  4.1267362249544004e+48
728  cost is  

927  cost is  3.246194742034883e+60
928  cost is  3.722660312540025e+60
929  cost is  4.269059900538597e+60
930  cost is  4.895658186430479e+60
931  cost is  5.614226465957997e+60
932  cost is  6.438263786149906e+60
933  cost is  7.383250538856931e+60
934  cost is  8.466939275895883e+60
935  cost is  9.709688209064468e+60
936  cost is  1.1134843660169138e+61
937  cost is  1.2769178645784175e+61
938  cost is  1.4643395836010818e+61
939  cost is  1.6792704335834105e+61
940  cost is  1.925748112451211e+61
941  cost is  2.2084029578820064e+61
942  cost is  2.5325449329788773e+61
943  cost is  2.904263379409769e+61
944  cost is  3.33054141197781e+61
945  cost is  3.8193871036426566e+61
946  cost is  4.379983925439071e+61
947  cost is  5.022863267461895e+61
948  cost is  5.760102281902596e+61
949  cost is  6.60555076482193e+61
950  cost is  7.575091338869114e+61
951  cost is  8.68693782474564e+61
952  cost is  9.961977406633023e+61
953  cost is  1.142416301951301e+62
954  cost is  1.31009633